import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { areas, services } from "./site-data.mjs";

const root=process.cwd(); const source=path.join(root,"site"); const config=JSON.parse(fs.readFileSync(path.join(root,"site.config.json"),"utf8")); const failures=[]; const records=[];
const walk=(dir)=>fs.readdirSync(dir,{withFileTypes:true}).flatMap((entry)=>entry.isDirectory()?walk(path.join(dir,entry.name)):[path.join(dir,entry.name)]);
const decode=(s)=>s.replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&gt;/g,">").replace(/&lt;/g,"<");
const textOf=(html)=>decode(html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim());
const routeOf=(file)=>{const rel=path.relative(source,file).replaceAll("\\","/"); return rel==="index.html"?"/":rel==="404.html"?"/404.html":`/${rel.replace(/index\.html$/,"")}`};
for(const required of ["index.html","404.html","assets/styles.css","assets/main.js","assets/favicon.svg"]){if(!fs.existsSync(path.join(source,required)))failures.push(`Missing ${required}`)}
for(const file of walk(source).filter((file)=>file.endsWith(".html"))){
  const html=fs.readFileSync(file,"utf8"); const route=routeOf(file); const rel=path.relative(root,file); const title=decode(html.match(/<title>([^<]+)<\/title>/i)?.[1]?.trim()||""); const h1s=[...html.matchAll(/<h1[^>]*>([\s\S]*?)<\/h1>/gi)].map((m)=>textOf(m[1])); const desc=html.match(/<meta name="description" content="([^"]+)"/i)?.[1]||""; const canonical=html.match(/<link rel="canonical" href="([^"]+)"/i)?.[1]||"";
  if(!title)failures.push(`Missing title: ${rel}`); if(h1s.length!==1)failures.push(`Expected one H1, found ${h1s.length}: ${rel}`); if(title!==h1s[0])failures.push(`Title/H1 mismatch: ${route} | title="${title}" h1="${h1s[0]||""}"`); if(!desc)failures.push(`Missing description: ${rel}`); if(!canonical)failures.push(`Missing canonical: ${rel}`);
  if(route!=="/404.html"&&!/Frequently asked questions/i.test(html))failures.push(`Missing visible FAQ eyebrow: ${route}`); if(!config.indexingEnabled&&!/name="robots" content="noindex, nofollow"/i.test(html))failures.push(`Missing pre-launch noindex: ${route}`);
  if(/\{\{[A-Z0-9_]+\}\}|\[TODO\b|\[PLACEHOLDER\]|REPLACE THIS|lorem ipsum/i.test(html))failures.push(`Unresolved placeholder: ${route}`);
  for(const match of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/gi)){try{JSON.parse(match[1])}catch{failures.push(`Invalid JSON-LD: ${route}`)}}
  for(const match of html.matchAll(/\b(?:href|src)="(\/[^"#?]*)/gi)){const ref=match[1]; const target=ref.endsWith("/")?path.join(source,ref.slice(1),"index.html"):path.join(source,ref.slice(1)); if(!fs.existsSync(target))failures.push(`Broken reference ${ref} on ${route}`)}
  const uniqueBlock=html.match(/<div data-unique-copy>([\s\S]*?)<\/div>\s*<section class="section (?:related|areas-block)/i)?.[1]; const mainHtml=html.match(/<main[^>]*>([\s\S]*?)<\/main>/i)?.[1]||"";
  records.push({file,route,title,h1:h1s[0]||"",desc,canonical,html,uniqueHtml:uniqueBlock||"",uniqueText:uniqueBlock?textOf(uniqueBlock):"",mainWords:textOf(mainHtml).split(/\s+/).filter(Boolean).length});
}
const duplicates=(key)=>{const map=new Map(); for(const record of records){const value=record[key];if(!value)continue;if(map.has(value))failures.push(`Duplicate ${key}: ${record.route} and ${map.get(value)}`);else map.set(value,record.route)}}; ["title","desc","canonical"].forEach(duplicates);
const serviceRecords=records.filter((r)=>/^\/services\/[^/]+\/$/.test(r.route)); const areaRecords=records.filter((r)=>/^\/service-areas\/[^/]+\/$/.test(r.route));
if(serviceRecords.length!==services.length)failures.push(`Expected ${services.length} service pages, found ${serviceRecords.length}`); if(areaRecords.length!==areas.length)failures.push(`Expected ${areas.length} area pages, found ${areaRecords.length}`);
for(const record of serviceRecords){if(!/id="related-services-heading">Related Services</.test(record.html))failures.push(`Missing Related Services: ${record.route}`); if(!/id="service-areas-heading">Service Areas for/.test(record.html))failures.push(`Missing Service Areas: ${record.route}`); const links=new Set([...record.html.matchAll(/href="(\/service-areas\/[^"#?]+\/)"/g)].map((m)=>m[1])); if(links.size!==areas.length)failures.push(`Service page ${record.route} links ${links.size}/${areas.length} area pages`)}
for(const record of areaRecords){if(!/id="area-services-heading">Plumbing Services Planned for/.test(record.html))failures.push(`Missing area service section: ${record.route}`); const links=new Set([...record.html.matchAll(/href="(\/services\/[^"#?]+\/)"/g)].map((m)=>m[1])); if(links.size!==services.length)failures.push(`Area page ${record.route} links ${links.size}/${services.length} service pages`)}
for(const record of [...serviceRecords,...areaRecords])if(record.mainWords<500||record.mainWords>1000)failures.push(`Visible main-content word count ${record.mainWords} outside 500-1000: ${record.route}`);
for(const record of records.filter((r)=>r.route!=="/404.html")){for(const service of services){if(!record.html.includes(`href="/services/${service.slug}/"`))failures.push(`Global service directory missing ${service.slug} on ${record.route}`)}for(const area of areas){if(!record.html.includes(`href="/service-areas/${area.slug}/"`))failures.push(`Global area directory missing ${area.slug} on ${record.route}`)}}

const uniqueRecords=records.filter((r)=>r.uniqueText); const normalize=(s)=>s.toLowerCase().replace(/[^a-z0-9\s]/g," ").replace(/\s+/g," ").trim(); const shingles=(s)=>{const words=normalize(s).split(" ");const set=new Set();for(let i=0;i<=words.length-5;i++)set.add(words.slice(i,i+5).join(" "));return set}; const jaccard=(a,b)=>{let intersection=0;for(const x of a)if(b.has(x))intersection++;return intersection/(a.size+b.size-intersection)}; let maxPair={score:0,a:"",b:""};
for(let i=0;i<uniqueRecords.length;i++){for(let j=i+1;j<uniqueRecords.length;j++){const score=jaccard(shingles(uniqueRecords[i].uniqueText),shingles(uniqueRecords[j].uniqueText));if(score>maxPair.score)maxPair={score,a:uniqueRecords[i].route,b:uniqueRecords[j].route};if(score>.65)failures.push(`Page-specific copy similarity ${(score*100).toFixed(1)}% exceeds 65%: ${uniqueRecords[i].route} and ${uniqueRecords[j].route}`)}}
const paragraphs=new Map(); for(const record of uniqueRecords){for(const p of [...record.uniqueHtml.matchAll(/<p[^>]*>([\s\S]*?)<\/p>/gi)].map((m)=>normalize(textOf(m[1]))).filter((p)=>p.split(" ").length>=12)){if(paragraphs.has(p)&&paragraphs.get(p)!==record.route)failures.push(`Exact duplicate page-specific paragraph: ${record.route} and ${paragraphs.get(p)}`);else paragraphs.set(p,record.route)}}
const report=`# Content and SEO Audit\n\nGenerated: ${new Date().toISOString()}\n\n## Inventory\n\n- HTML pages: ${records.length}\n- Service pages: ${serviceRecords.length}\n- Service-area pages: ${areaRecords.length}\n- Page-specific content blocks compared: ${uniqueRecords.length}\n\n## Alignment checks\n\n- Every HTML page has exactly one H1.\n- Every title tag exactly equals its visible H1.\n- Titles, meta descriptions, and canonical URLs are unique.\n- Every service page links to all ${areas.length} intended market pages.\n- Every market page links to all ${services.length} service pages.\n- Complete service and market directories appear in crawlable global navigation/footer HTML.\n\n## Uniqueness analysis\n\n- Exact duplicate page-specific paragraphs: ${failures.filter((f)=>f.startsWith("Exact duplicate")).length}\n- Highest five-word-shingle similarity: ${(maxPair.score*100).toFixed(1)}%\n- Closest pair: ${maxPair.a} and ${maxPair.b}\n- Failure threshold: 72.0%\n- Result: ${failures.length?"FAIL — see command output":"PASS"}\n\nShared navigation, footer directories, disclosure language, and required component labels are treated as sitewide interface content rather than page-specific body copy.\n`;
fs.writeFileSync(path.join(root,"CONTENT-AUDIT.md"),report.replace("Failure threshold: 72.0%","Failure threshold: 65.0%"),"utf8");
if(failures.length){console.error(failures.map((f)=>`- ${f}`).join("\n"));process.exit(1)} console.log(`Site checks passed. ${records.length} pages; maximum page-specific similarity ${(maxPair.score*100).toFixed(1)}%.`);
