import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { areas, project } from "./site-data.mjs";
const root=process.cwd(),source=path.join(root,"site"),config=JSON.parse(fs.readFileSync(path.join(root,"site.config.json"),"utf8")),fail=[],records=[];
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]),decode=s=>s.replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&gt;/g,">").replace(/&lt;/g,"<"),text=h=>decode(h.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()),route=f=>{const r=path.relative(source,f).replaceAll("\\","/");return r==="index.html"?"/":r==="404.html"?"/404.html":`/${r.replace(/index\.html$/,"")}`};
for(const req of ["index.html","404.html","assets/styles.css","assets/main.js","assets/favicon.svg"])if(!fs.existsSync(path.join(source,req)))fail.push(`Missing ${req}`);
for(const file of walk(source).filter(f=>f.endsWith(".html"))){const h=fs.readFileSync(file,"utf8"),r=route(file),title=decode(h.match(/<title>([^<]+)<\/title>/i)?.[1]?.trim()||""),h1=[...h.matchAll(/<h1[^>]*>([\s\S]*?)<\/h1>/gi)].map(m=>text(m[1])),desc=h.match(/<meta name="description" content="([^"]+)"/i)?.[1]||"",canonical=h.match(/<link rel="canonical" href="([^"]+)"/i)?.[1]||"",unique=h.match(/<div data-unique-copy>([\s\S]*?)<\/div>\s*<section class="section (?:related|nearby)/i)?.[1]||"",faqHtml=h.match(/<section class="section faq"[\s\S]*?<\/section>/i)?.[0]||"",mainHtml=h.match(/<main[^>]*>([\s\S]*?)<\/main>/i)?.[1]||"";if(h1.length!==1)fail.push(`H1 count ${h1.length}: ${r}`);if(title!==h1[0])fail.push(`Title/H1 mismatch: ${r}`);if(!desc)fail.push(`Missing description: ${r}`);if(!canonical)fail.push(`Missing canonical: ${r}`);if(r!=="/404.html"&&!/Frequently asked questions/i.test(h))fail.push(`Missing FAQ: ${r}`);if(!config.indexingEnabled&&!/name="robots" content="noindex, nofollow"/.test(h))fail.push(`Missing noindex: ${r}`);if(/\{\{[A-Z0-9_]+\}\}|\[TODO\b|\[PLACEHOLDER\]|REPLACE THIS|lorem ipsum/i.test(h))fail.push(`Placeholder: ${r}`);for(const m of h.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/gi)){try{JSON.parse(m[1])}catch{fail.push(`Invalid JSON-LD: ${r}`)}}for(const m of h.matchAll(/\b(?:href|src)="(\/[^"#?]*)/gi)){const ref=m[1],target=ref.endsWith("/")?path.join(source,ref.slice(1),"index.html"):path.join(source,ref.slice(1));if(!fs.existsSync(target))fail.push(`Broken ${ref}: ${r}`)}records.push({r,title,desc,canonical,h,uniqueHtml:unique,faqHtml,uniqueText:text(unique),faqText:text(faqHtml),mainWords:text(mainHtml).split(/\s+/).filter(Boolean).length})}
for(const key of ["title","desc","canonical"]){const seen=new Map();for(const x of records){if(seen.has(x[key]))fail.push(`Duplicate ${key}: ${x.r} and ${seen.get(x[key])}`);else seen.set(x[key],x.r)}}
const sr=records.filter(x=>/^\/services\/[^/]+\/$/.test(x.r)),ar=records.filter(x=>/^\/service-areas\/[^/]+\/$/.test(x.r));if(sr.length!==project.services.length)fail.push(`Service page count ${sr.length}/${project.services.length}`);if(ar.length!==areas.length)fail.push(`Area page count ${ar.length}/${areas.length}`);
for(const x of sr){const slug=x.r.split("/")[2],service=project.services.find(s=>s.slug===slug),serviceIntro=x.h.match(/<main id="main-content">([\s\S]*?)<section class="section" aria-labelledby="service-area-title">/i)?.[1]||"";if(!service)fail.push(`Unknown service route: ${x.r}`);else if(x.title!==service.label)fail.push(`Service title/H1 must equal label: ${x.r}`);if(/\b(?:Houston|Texas|Greater Houston|TX)\b/i.test(text(serviceIntro)))fail.push(`Location modifier before area links: ${x.r}`);if(/\b(?:Houston|Texas|Greater Houston|TX)\b/i.test(x.desc))fail.push(`Location modifier in service description: ${x.r}`);if(!/id="related-title">Related Services/.test(x.h))fail.push(`Missing related services: ${x.r}`);if(!/id="service-area-title">Service Areas/.test(x.h))fail.push(`Missing service areas: ${x.r}`);const a=new Set([...x.h.matchAll(/href="(\/service-areas\/[^"#?]+\/)"/g)].map(m=>m[1]));if(a.size!==areas.length)fail.push(`Area links ${a.size}/${areas.length}: ${x.r}`)}
for(const x of ar){if(!/id="area-service-title">/.test(x.h))fail.push(`Missing area service section: ${x.r}`);const s=new Set([...x.h.matchAll(/href="(\/services\/[^"#?]+\/)"/g)].map(m=>m[1]));if(s.size!==project.services.length)fail.push(`Service links ${s.size}/${project.services.length}: ${x.r}`)}
for(const x of [...sr,...ar])if(x.mainWords<500||x.mainWords>1000)fail.push(`Visible main-content word count ${x.mainWords} outside 500-1000: ${x.r}`);
for(const x of records.filter(x=>x.r!=="/404.html")){for(const s of project.services)if(!x.h.includes(`href="/services/${s.slug}/"`))fail.push(`Global service missing ${s.slug}: ${x.r}`);for(const a of areas)if(!x.h.includes(`href="/service-areas/${a.slug}/"`))fail.push(`Global area missing ${a.slug}: ${x.r}`)}
const norm=s=>s.toLowerCase().replace(/[^a-z0-9\s]/g," ").replace(/\s+/g," ").trim(),shingle=s=>{const w=norm(s).split(" "),set=new Set();for(let i=0;i<=w.length-5;i++)set.add(w.slice(i,i+5).join(" "));return set},jac=(a,b)=>{let n=0;for(const v of a)if(b.has(v))n++;return n/(a.size+b.size-n)};let max={score:0,a:"",b:""};const uniq=records.filter(x=>x.uniqueText).map(x=>({...x,comparisonText:`${x.uniqueText} ${x.faqText}`}));for(let i=0;i<uniq.length;i++)for(let j=i+1;j<uniq.length;j++){const score=jac(shingle(uniq[i].comparisonText),shingle(uniq[j].comparisonText));if(score>max.score)max={score,a:uniq[i].r,b:uniq[j].r};if(score>.65)fail.push(`Similarity ${(score*100).toFixed(1)}% exceeds 65%: ${uniq[i].r} / ${uniq[j].r}`)}const paras=new Map(),questions=new Map(),answers=new Map();for(const x of uniq){for(const p of [...(`${x.uniqueHtml}${x.faqHtml}`).matchAll(/<p[^>]*>([\s\S]*?)<\/p>/gi)].map(m=>norm(text(m[1]))).filter(p=>p.split(" ").length>=12)){if(paras.has(p)&&paras.get(p)!==x.r)fail.push(`Duplicate paragraph: ${x.r} / ${paras.get(p)}`);else paras.set(p,x.r)}for(const q of [...x.faqHtml.matchAll(/<summary>([\s\S]*?)<span>/gi)].map(m=>norm(text(m[1])))){if(questions.has(q))fail.push(`Duplicate FAQ question: ${x.r} / ${questions.get(q)}`);else questions.set(q,x.r)}for(const a of [...x.faqHtml.matchAll(/<details>[\s\S]*?<p>([\s\S]*?)<\/p>[\s\S]*?<\/details>/gi)].map(m=>norm(text(m[1])))){if(answers.has(a))fail.push(`Duplicate FAQ answer: ${x.r} / ${answers.get(a)}`);else answers.set(a,x.r)}}
fs.writeFileSync(path.join(root,"CONTENT-AUDIT.md"),`# Content and SEO Audit\n\n- Project: ${project.name}\n- HTML pages: ${records.length}\n- Service pages: ${sr.length}\n- Area pages: ${ar.length}\n- Substantive pages at 500-1,000 words: ${[...sr,...ar].filter(x=>x.mainWords>=500&&x.mainWords<=1000).length}/${sr.length+ar.length}\n- Page-specific blocks and FAQs compared: ${uniq.length}\n- Exact duplicate page-specific paragraphs: ${fail.filter(x=>x.startsWith("Duplicate paragraph")).length}\n- Duplicate FAQ questions: ${fail.filter(x=>x.startsWith("Duplicate FAQ question")).length}\n- Duplicate FAQ answers: ${fail.filter(x=>x.startsWith("Duplicate FAQ answer")).length}\n- Maximum five-word-shingle similarity: ${(max.score*100).toFixed(1)}%\n- Closest pair: ${max.a} and ${max.b}\n- Failure threshold: 65.0%\n- Result: ${fail.length?"FAIL":"PASS"}\n\nTitles equal H1s; service-page titles, H1s, descriptions, and pre-area-link content contain no location modifiers; titles, descriptions, and canonicals are unique; reciprocal service/area linking and complete crawlable directories are enforced.\n`,"utf8");
if(fail.length){console.error(fail.map(x=>`- ${x}`).join("\n"));process.exit(1)}console.log(`${project.name} checks passed: ${records.length} pages; max similarity ${(max.score*100).toFixed(1)}%.`);
