import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { areas, project } from "./site-data.mjs";
const root=process.cwd(), today=new Date().toISOString().slice(0,10), clean=v=>String(v).replaceAll("|","/").replaceAll("\n"," ");
const siteConfig=JSON.parse(fs.readFileSync(path.join(root,"site.config.json"),"utf8"));
const hasProductionDomain=!siteConfig.baseUrl.endsWith(".invalid");
const rows=["# Keyword Map","",`Generated from the shared service and market data for ${project.name}. Service pages intentionally use topic-only keywords and headings; Houston is added to the research query for local SERP comparison, while location intent belongs to the service-area pages. See SERP-CONTENT-GAPS.md for live result evidence and page-specific gap assignments.`,"","## Homepage target","","| Broadest topic keyword | Greater-area modifier | Required H1 and exact title | Primary homepage services | Decision |","| --- | --- | --- | --- | --- |",`| ${project.topic.toLowerCase()} | Greater Houston Area | ${project.homepageH1} | ${project.services.slice(0,8).map(s=>s.label).join("; ")} | Approve |`,"","## Service targets","","| Service | Published primary keyword | Houston research query | Canonical | Required H1 and exact title | Group | Related services | Area links | Decision |","| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"]; 
for(const s of project.services)rows.push(`| ${clean(s.label)} | ${clean(s.keyword)} | ${clean(s.label)} Houston TX | /services/${s.slug}/ | ${clean(s.h1)} | ${clean(s.group)} | ${s.related.map(x=>`/services/${x}/`).join("; ")} | All ${areas.length} area guides | Approve |`);
rows.push("","## Candidate consolidation and cannibalization rules","","- Wording-only synonyms merge into the nearest approved service owner.","- The site does not create separate emergency, 24-hour, near-me, price, cost, or ZIP-code doorway pages.","- Service pages are separated only by material system, symptom, diagnostic deliverable, work method, property type, safety scope, or maintenance intent.","- Unsupported specialties, guaranteed response times, pricing claims, and credentials remain excluded until an operator verifies them.","","## Service-area targets","","| Area | Region | Coverage | Primary keyword and research query | Canonical | Required H1 and exact title | Unique local value | Decision |","| --- | --- | --- | --- | --- | --- | --- | --- | --- |");
for(const a of areas)rows.push(`| ${clean(a.label)} | ${clean(a.region)} | Intended pending verification | ${project.topic.toLowerCase()} ${clean(a.label)} TX | /service-areas/${a.slug}/ | ${project.topic} in ${clean(a.label)}, TX | ${project.topic}-specific property, access, system, and jurisdiction planning | Approve |`);
rows.push("","## Linking rules","",`- Every service page links to four mapped related services and all ${areas.length} area pages.`,`- Every area page links to all ${project.services.length} service pages and regional peer markets.`,`- Desktop navigation, mobile submenus, footer directories, route generation, keyword map, and audits share one data source.`,`- Title tags exactly equal their page H1s.`);
fs.writeFileSync(path.join(root,"KEYWORD-MAP.md"),rows.join("\n")+"\n","utf8");
const routeRows=[["/","Home",project.topic.toLowerCase(),project.homepageH1],["/services/","Directory",`${project.topic.toLowerCase()} services`,`${project.topic} Services`],...project.services.map(s=>[`/services/${s.slug}/`,`Service`,s.keyword,s.h1]),["/service-areas/","Directory",`${project.topic.toLowerCase()} service areas Greater Houston`,`${project.topic} Service Areas in Greater Houston`],...areas.map(a=>[`/service-areas/${a.slug}/`,`Area`,`${project.topic.toLowerCase()} ${a.label} TX`,`${project.topic} in ${a.label}, TX`]),["/process/","Information",`${project.topic.toLowerCase()} service process`,`How ${project.topic} Service Works`],["/contact/","Conversion",`${project.topic.toLowerCase()} service request`,`Request ${project.topic} Service`],["/privacy/","Legal","privacy information",`Privacy Information for ${project.name}`],["/404.html","Utility","not indexable","Page Not Found"]];
fs.writeFileSync(path.join(root,"ROUTE-INVENTORY.csv"),"route,type,primary_keyword,title_and_h1\n"+routeRows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(",")).join("\n")+"\n","utf8");
const brief=`# Project Brief\n\n- Project: ${project.name}\n- Operating status: Rank-and-rent property awaiting an operator\n- Primary niche: ${project.topic}\n- Primary market: Greater Houston, Texas\n- Domain: Undecided; reserved placeholder in site.config.json\n- Phone: Form-only; no active number supplied\n- Address: None\n- Google Business Profile: Not eligible for this lead-generation property\n- Lead destination: Not connected\n- Deployment: Not requested\n- Stack: Portable zero-dependency static HTML/CSS/JavaScript\n- Pages: ${routeRows.length} total; ${project.services.length} services; ${areas.length} hyper-local markets\n- Indexing: Disabled until domain, operator, coverage, privacy, and routing verification\n- Analytics: None\n- Verified business claims: None supplied; no reviews, licenses, hours, guarantees, prices, staff, or address published\n`;
fs.writeFileSync(path.join(root,"PROJECT-BRIEF.md"),brief,"utf8");
fs.writeFileSync(path.join(root,"BUILD-REQUEST.md"),`# Build Request\n\nBuild ${project.name} locally as an independent Greater Houston rank-and-rent website. Create a distinct ${project.topic.toLowerCase()} service architecture, ${areas.length} useful hyper-local market pages, reciprocal internal linking, exact title/H1 alignment, unique FAQs and content, a non-routing form, technical SEO files, automated duplicate-content checks, and a portable production package. Do not deploy or invent business facts.\n`,`utf8`);
const blockers=`# Launch Blockers\n\n- [ ] Contract with and verify a real operator.\n- [ ] Verify applicable licenses, insurance, equipment, services, operating model, and every ZIP-code/service combination.\n- [ ] Select a production domain; replace baseUrl and enable indexing only after all launch checks.\n- [ ] Connect a secure form endpoint, verified recipients, spam controls, consent, monitoring, retention, and deletion procedures.\n- [ ] Add a monitored business and privacy email.\n- [ ] Add an active controlled phone only after routing is tested.\n- [ ] Keep future, virtual, mailbox, private, and unstaffed addresses out of public content and schema.\n- [ ] Do not create a Google Business Profile for the lead-generation property.\n- [ ] Re-check current Texas licensing and exact local permit requirements.\n- [ ] Add analytics or call tracking only with required privacy and consent updates.\n- [ ] Run npm run build and complete a live-domain smoke test.\n`;
fs.writeFileSync(path.join(root,"LAUNCH-BLOCKERS.md"),blockers,"utf8");
const readme=`# ${project.name}\n\nPortable static rank-and-rent build with ${routeRows.length} pages, ${project.services.length} intent-mapped service pages, and ${areas.length} hyper-local Greater Houston area pages.\n\n## Commands\n\n\`\`\`powershell\nnpm install\nnpm run dev\nnpm run check\nnpm run build\n\`\`\`\n\nLocal preview: http://localhost:${project.previewPort}/\n\nProduction output: dist/\n\nThe source of truth is scripts/site-data.mjs. Generated HTML, KEYWORD-MAP.md, and ROUTE-INVENTORY.csv should be changed through the shared data and generator. The current build is intentionally noindex and form-only. Resolve LAUNCH-BLOCKERS.md before deployment.\n`;
fs.writeFileSync(path.join(root,"README.md"),readme,"utf8");
const handoff=`# Website Handoff\n\n- Project: ${project.name}\n- Delivery date: ${today}\n- Source: this project directory\n- Production output: dist/\n- Install: npm install\n- Preview: npm run dev at http://localhost:${project.previewPort}/\n- Build: npm run build\n- Phone: None\n- Form: Browser-only validation; no destination\n- Address: None\n- GBP: Not eligible for the rank-and-rent property\n- Canonical: Reserved .invalid placeholder\n- Robots: Full disallow while pre-launch\n- Analytics: None\n- Environment variables: None\n\n## Verified\n\n- [x] Exact title/H1 alignment\n- [x] Unique titles, descriptions, and canonicals\n- [x] Unique page-specific FAQs and substantive copy\n- [x] Complete services and markets in navigation, footer, and sitemap generation\n- [x] Four related-service links and all market links on every service page\n- [x] All service links and regional peer links on every area page\n- [x] Structured data JSON parsing\n- [x] Broken-link and orphan checks\n- [x] Pre-launch phone/address/GBP truth rules\n- [x] Production build\n\nSee CONTENT-AUDIT.md and LAUNCH-BLOCKERS.md.\n`;
fs.writeFileSync(path.join(root,"HANDOFF.md"),handoff,"utf8");
if(hasProductionDomain){
  const replaceIn=(file,replacements)=>{
    const target=path.join(root,file);
    let content=fs.readFileSync(target,"utf8");
    for(const [from,to] of replacements)content=content.replace(from,to);
    fs.writeFileSync(target,content,"utf8");
  };
  replaceIn("PROJECT-BRIEF.md",[
    ["- Domain: Undecided; reserved placeholder in site.config.json",`- Domain: ${siteConfig.baseUrl}`],
    ["- Deployment: Not requested","- Deployment: Vercel production, noindex"],
    ["- Indexing: Disabled until domain, operator, coverage, privacy, and routing verification","- Indexing: Disabled until operator, coverage, privacy, and routing verification"]
  ]);
  replaceIn("LAUNCH-BLOCKERS.md",[
    ["- [ ] Select a production domain; replace baseUrl and enable indexing only after all launch checks.","- [x] Select a production domain and replace the placeholder baseUrl.\n- [ ] Enable indexing only after all operator and launch checks pass."]
  ]);
  replaceIn("HANDOFF.md",[["- Canonical: Reserved .invalid placeholder",`- Canonical: ${siteConfig.baseUrl}`]]);
}
console.log(`Generated project documents for ${routeRows.length} routes.`);
