export const site = {
  name: "Houston Mold Remediation Pros",
  description: "Independent mold remediation service-matching resource for the Greater Houston area.",
  status: "Pre-launch service-matching website — provider coverage must be verified",
};

export const services = [
  {
    slug: "mold-remediation",
    label: "Mold Remediation",
    keyword: "mold remediation Houston",
    h1: "Mold Remediation in Houston, TX",
    group: "Core remediation",
    priority: true,
    lede: "Mold remediation addresses affected materials, limits cross-contamination, and pairs cleanup with a plan for the moisture source. This page explains the broad remediation pathway without replacing a site-specific assessment.",
    problemHeading: "When professional mold remediation may be appropriate",
    problemText: "A professional scope may be useful when growth covers more than a small isolated surface, returns after cleaning, involves porous materials, follows a major water event, or may be hidden inside an assembly.",
    signals: [
      ["Visible or recurring growth", "Repeated staining or growth can point to unresolved moisture or contaminated material beyond the surface."],
      ["Porous building materials", "Drywall, insulation, carpet backing, ceiling tile, and composite wood may require removal rather than surface wiping."],
      ["Occupied or sensitive spaces", "Containment, sequencing, access, and communication matter when a home or workplace remains occupied."],
    ],
    scopeHeading: "What a remediation scope should make clear",
    scopeText: "A useful proposal identifies containment, affected materials, removal or cleaning methods, debris handling, drying expectations, moisture-source responsibilities, and the conditions for completing the work.",
    scopeItems: ["Affected rooms and materials", "Containment and pressure-control plan", "Removal, cleaning, and disposal steps", "Moisture correction and drying responsibilities", "Documentation and post-work verification"],
    decisionHeading: "Remediation is not the same as assessment",
    decisionText: "Texas regulates mold assessment and remediation as separate roles in projects where the state rules apply. A future provider match must respect that separation and identify when an independent assessment consultant should define or verify the scope.",
    related: ["residential-mold-remediation", "commercial-mold-remediation", "mold-inspection-testing", "water-damage-mold-cleanup", "black-mold-remediation", "dehumidification-moisture-control"],
    faqs: [
      ["What is included in mold remediation?", "The exact scope varies, but it commonly covers containment, removal or cleaning of affected materials, controlled debris handling, and coordination with moisture correction."],
      ["Is mold removal the same as mold remediation?", "The terms are often used together. Remediation is the broader idea because it addresses affected materials, spread control, cleanup, and the conditions that allowed growth."],
      ["Does every mold concern require testing first?", "No. Testing should answer a defined question. Larger or regulated projects may require an independent Texas mold assessment consultant to establish a protocol."],
      ["How is the service area confirmed?", "This is a pre-launch matching site. A real provider and ZIP-code coverage must be verified before any request is routed."],
    ],
  },
  {
    slug: "residential-mold-remediation",
    label: "Residential Mold Remediation",
    keyword: "residential mold remediation Houston",
    h1: "Residential Mold Remediation in Houston, TX",
    group: "Core remediation",
    priority: true,
    lede: "Residential mold remediation needs to account for occupants, belongings, pets, room access, and the moisture pathway behind the affected area. The scope should fit the home rather than rely on a one-size-fits-all treatment.",
    problemHeading: "Common mold pathways in Houston homes",
    problemText: "Roof leaks, plumbing failures, wet bathrooms, appliance overflows, long air-conditioning seasons, and storm-driven water can affect materials that stay damp after the visible water is gone.",
    signals: [
      ["Walls and ceilings", "Discoloration after a leak may involve drywall cavities, insulation, framing, or an adjacent room."],
      ["Kitchens and bathrooms", "Supply lines, drains, pans, grout, cabinets, and ventilation can create different moisture patterns."],
      ["Bedrooms and living areas", "Occupancy planning and containment become important when work is near sleeping or high-use spaces."],
    ],
    scopeHeading: "Planning remediation around a household",
    scopeText: "A residential plan should explain what rooms remain accessible, how belongings are protected, whether occupants need to leave the work zone, and who is responsible for plumbing, roofing, HVAC, or reconstruction.",
    scopeItems: ["Occupant and pet considerations", "Belongings and furniture protection", "Containment around living spaces", "Source repair and drying coordination", "Reconstruction boundaries"],
    decisionHeading: "Small surface growth and hidden damage are different problems",
    decisionText: "A minor bathroom surface issue does not have the same scope as growth behind cabinets after a supply-line leak. Location, material, extent, and moisture history determine the appropriate next step.",
    related: ["mold-remediation", "attic-mold-remediation", "water-damage-mold-cleanup", "bathroom-mold-remediation", "mold-odor-removal", "mold-inspection-testing"],
    faqs: [
      ["Can a family remain home during remediation?", "It depends on the work area, containment plan, occupant sensitivities, and provider guidance. The proposal should state access restrictions before work begins."],
      ["What should be moved before residential mold work?", "The provider should identify belongings that can stay protected, items that need cleaning, and anything that must be removed from the work zone."],
      ["Who repairs the leak that caused the mold?", "Remediation and source repair may involve different trades. The scope should assign roofing, plumbing, HVAC, drainage, or reconstruction responsibilities clearly."],
      ["Can a request be submitted without a phone number?", "Yes. The current test form accepts an email address or phone number, but it does not transmit until a verified operator and destination are connected."],
    ],
  },
  {
    slug: "commercial-mold-remediation",
    label: "Commercial Mold Remediation",
    keyword: "commercial mold remediation Houston",
    h1: "Commercial Mold Remediation in Houston, TX",
    group: "Core remediation",
    priority: true,
    lede: "Commercial mold remediation combines material cleanup with operational planning. Occupancy, tenant communication, after-hours access, documentation, and phased work can be as important as the physical remediation method.",
    problemHeading: "Commercial conditions that change the response",
    problemText: "A leaking roof over an office, a failed condensate line in a retail space, and chronic humidity in a warehouse require different access plans, specialists, and business-continuity decisions.",
    signals: [
      ["Occupied workplaces", "Containment, pathways, work hours, and employee communication should be coordinated before work starts."],
      ["Multi-tenant buildings", "The moisture source or affected assembly may cross suite, floor, or ownership boundaries."],
      ["Records and risk management", "Photos, protocols, daily logs, disposal records, and clearance documents may be needed by stakeholders."],
    ],
    scopeHeading: "A commercial plan should address operations",
    scopeText: "The scope should identify work zones, building-system shutdowns, access windows, affected inventory or equipment, escalation contacts, and the documents required for reopening or tenant handoff.",
    scopeItems: ["Phased containment and access", "Tenant and employee communication", "HVAC and building-system coordination", "Inventory or equipment protection", "Documentation and verification"],
    decisionHeading: "Property type determines the team",
    decisionText: "Offices, retail centers, schools, healthcare spaces, hospitality properties, and industrial buildings can require different safety plans and qualified trades. A provider match must be based on the actual occupancy and scope.",
    related: ["mold-remediation", "apartment-multifamily-mold-remediation", "hvac-mold-remediation", "water-damage-mold-cleanup", "mold-inspection-testing", "indoor-air-quality-testing"],
    faqs: [
      ["Can commercial remediation happen after business hours?", "Often it can be phased around operations, but access, noise, HVAC shutdowns, security, and cure or drying time must be included in the plan."],
      ["Who receives commercial project documentation?", "That depends on the property. Owners, managers, tenants, insurers, consultants, or risk teams may each require specific records."],
      ["Does a commercial building need independent clearance?", "It may. The applicable Texas rules, project size, protocol, lease requirements, and stakeholder expectations should be reviewed before work."],
      ["Are all commercial property types covered?", "Not yet. The site is awaiting an operator, so capability and ZIP-code coverage must be confirmed for each property and service."],
    ],
  },
  {
    slug: "apartment-multifamily-mold-remediation",
    label: "Apartment & Multifamily Mold Remediation",
    keyword: "apartment mold remediation Houston",
    h1: "Apartment Mold Remediation in Houston, TX",
    group: "Property-specific",
    priority: true,
    lede: "Apartment mold remediation requires coordination among residents, property management, ownership, maintenance, consultants, and contractors. Shared walls and building systems can make a single-unit complaint part of a wider moisture problem.",
    problemHeading: "Why multifamily mold concerns cross boundaries",
    problemText: "Stacked plumbing, shared roof systems, exterior envelopes, common HVAC configurations, and adjacent units can move water or complicate access beyond the first visible area.",
    signals: [
      ["Repeated unit complaints", "Similar concerns in adjacent or stacked units may point to a shared source that needs broader investigation."],
      ["Turnover and vacancy work", "Vacant-unit schedules can create access opportunities but should not replace a defined assessment and moisture plan."],
      ["Resident communication", "Entry notices, temporary access restrictions, belongings, and accommodation decisions require a documented process."],
    ],
    scopeHeading: "Information managers should organize first",
    scopeText: "Maintenance history, leak records, prior repairs, unit diagrams, resident reports, and photographs can help an assessor or remediator understand whether the issue is isolated or building-related.",
    scopeItems: ["Unit and adjacent-unit history", "Shared plumbing and envelope systems", "Resident access and communication", "Maintenance and repair records", "Ownership and insurance contacts"],
    decisionHeading: "A unit-by-unit cleanup may miss a shared source",
    decisionText: "Treating the visible room without tracing stacked supply lines, roof drainage, exterior penetrations, or common mechanical systems can leave the moisture pathway unresolved.",
    related: ["commercial-mold-remediation", "residential-mold-remediation", "mold-inspection-testing", "water-damage-mold-cleanup", "hvac-mold-remediation", "mold-odor-removal"],
    faqs: [
      ["Who should submit an apartment mold request?", "A resident, owner, manager, or authorized representative can describe the concern, but access and contracting authority must be confirmed before work."],
      ["Should adjacent units be considered?", "Yes when plumbing, roofs, walls, or mechanical systems are shared. An assessor can determine whether additional areas should be evaluated."],
      ["Can remediation be completed during unit turnover?", "Possibly, but vacancy does not eliminate the need to identify the moisture source, define the work, and document completion."],
      ["Does this site represent a property manager or contractor?", "No. It is an independent pre-launch service-matching property and does not yet have an activated local operator."],
    ],
  },
  {
    slug: "attic-mold-remediation",
    label: "Attic Mold Remediation",
    keyword: "attic mold remediation Houston",
    h1: "Attic Mold Remediation in Houston, TX",
    group: "Property-specific",
    priority: true,
    lede: "Attic mold remediation must account for roof intrusion, air leakage, insulation, ventilation, and attic HVAC equipment. Cleaning roof decking without correcting the moisture pathway can allow the condition to return.",
    problemHeading: "Moisture pathways above the ceiling",
    problemText: "Houston attics combine extreme heat, outdoor humidity, roof exposure, and often air handlers or ductwork. Water can travel along decking and framing before a ceiling stain appears.",
    signals: [
      ["Roof leaks and penetrations", "Flashing, vents, valleys, chimneys, and storm damage can admit water away from the visible mark."],
      ["Condensation and air leakage", "Warm humid air meeting cooler surfaces can damp decking, ducts, boots, or insulation."],
      ["Attic HVAC equipment", "Drain pans, condensate lines, air handlers, and damaged duct insulation can add localized moisture."],
    ],
    scopeHeading: "What the attic scope should identify",
    scopeText: "The plan should distinguish surface cleaning from material removal, identify inaccessible cavities, address wet insulation, and assign roofing, HVAC, air-sealing, ventilation, or insulation corrections.",
    scopeItems: ["Roof-deck and framing condition", "Wet or contaminated insulation", "Ventilation and air-sealing issues", "HVAC drainage and duct condition", "Roof-repair coordination"],
    decisionHeading: "Dark roof decking is not a species diagnosis",
    decisionText: "Staining, dirt, old water marks, and microbial growth can look similar. Visual color alone does not identify the material or determine the required scope.",
    related: ["residential-mold-remediation", "hvac-mold-remediation", "water-damage-mold-cleanup", "mold-inspection-testing", "dehumidification-moisture-control", "specialty-remediation"],
    faqs: [
      ["Does attic mold mean the roof must be replaced?", "Not necessarily. The source may involve a localized leak, air leakage, condensation, ventilation, or HVAC drainage. A qualified evaluation should identify the pathway."],
      ["Can attic insulation remain in place?", "It depends on moisture, contamination, access, and the remediation plan. Wet or obstructive insulation may need removal or replacement."],
      ["Is ventilation always the cause of attic mold?", "No. Roof intrusion, bath exhaust, air leakage, condensate, and duct issues can create similar conditions."],
      ["Should an attic HVAC unit be inspected too?", "Yes when moisture or growth is near the air handler, drain system, boots, or ductwork."],
    ],
  },
  {
    slug: "crawl-space-mold-remediation",
    label: "Crawl-Space Mold Remediation",
    keyword: "crawl space mold remediation Houston",
    h1: "Crawl-Space Mold Remediation in Houston, TX",
    group: "Property-specific",
    priority: true,
    lede: "Crawl-space mold remediation should address subfloor framing, insulation, plumbing, drainage, duct condensation, and ground moisture. Cleanup alone is unlikely to hold if the space remains wet or humid.",
    problemHeading: "How crawl spaces stay damp",
    problemText: "Low drainage, plumbing leaks, wet soil, foundation openings, damaged vapor barriers, and cool ducts exposed to humid air can keep the subfloor environment damp.",
    signals: [
      ["Standing water or wet soil", "Surface drainage, downspouts, grading, or plumbing may be contributing water below the home."],
      ["Condensation on ducts", "Cool surfaces can collect moisture when humid outside air enters the crawl space."],
      ["Wet insulation and framing", "Absorbent materials can hold moisture and obstruct inspection of joists or subflooring."],
    ],
    scopeHeading: "A crawl-space scope needs a water plan",
    scopeText: "The provider should explain access, containment, debris removal, wood cleaning, insulation handling, drying, drainage, vapor control, and whether encapsulation is appropriate after correction.",
    scopeItems: ["Foundation access and work clearance", "Groundwater and drainage conditions", "Plumbing and condensate leaks", "Duct and insulation condition", "Vapor barrier or encapsulation plan"],
    decisionHeading: "Encapsulation follows diagnosis",
    decisionText: "Sealing a crawl space without correcting bulk water, drying wet materials, and addressing contamination can hide rather than solve the problem.",
    related: ["crawl-space-encapsulation", "residential-mold-remediation", "water-damage-mold-cleanup", "dehumidification-moisture-control", "hvac-mold-remediation", "mold-inspection-testing"],
    faqs: [
      ["Is crawl-space encapsulation always required?", "No. It can be one moisture-control option, but drainage, leaks, contaminated materials, and drying must be addressed first."],
      ["Why does a crawl space smell affect the house?", "Air movement through floor penetrations and duct systems can carry odors and humidity into occupied rooms."],
      ["Can wet crawl-space insulation be cleaned?", "The material type and condition matter. Saturated or contaminated porous insulation often cannot be restored reliably."],
      ["What details help with provider matching?", "Share the foundation type, access size, standing-water history, visible materials, plumbing or duct involvement, and ZIP code."],
    ],
  },
  {
    slug: "crawl-space-encapsulation",
    label: "Crawl-Space Encapsulation",
    keyword: "crawl space encapsulation Houston",
    h1: "Crawl-Space Encapsulation in Houston, TX",
    group: "Moisture control",
    priority: false,
    lede: "Crawl-space encapsulation uses ground and foundation barriers, air sealing, drainage, and sometimes conditioned drying to manage moisture below a building. It should be designed around existing water and material conditions.",
    problemHeading: "What encapsulation is intended to control",
    problemText: "An encapsulation assembly can reduce ground-vapor entry and uncontrolled outside air, but it cannot substitute for repairing plumbing leaks, bulk-water intrusion, or damaged structural materials.",
    signals: [
      ["Exposed soil", "A continuous ground barrier can reduce vapor movement when seams and penetrations are detailed correctly."],
      ["Open vents and air leakage", "Foundation openings and floor penetrations influence humidity and communication with occupied space."],
      ["Drainage limitations", "Low points, groundwater, and exterior runoff need a plan before the liner is installed."],
    ],
    scopeHeading: "Components of an encapsulation proposal",
    scopeText: "The proposal should describe liner thickness and fastening, seam treatment, pier and penetration details, drainage, access doors, humidity targets, monitoring, and any dehumidification or conditioned-air strategy.",
    scopeItems: ["Ground and wall liner details", "Seams, piers, and penetrations", "Exterior and interior drainage", "Vent and access-door treatment", "Humidity control and monitoring"],
    decisionHeading: "Remediation and encapsulation are separate scopes",
    decisionText: "Existing mold or water-damaged material may need assessment and remediation before the moisture-control assembly is installed. The responsible parties and sequence should be explicit.",
    related: ["crawl-space-mold-remediation", "dehumidification-moisture-control", "residential-mold-remediation", "water-damage-mold-cleanup", "mold-inspection-testing"],
    faqs: [
      ["Will encapsulation remove existing mold?", "No. Encapsulation is a moisture-control system. Existing contamination and damaged materials require their own evaluation and scope."],
      ["Does every encapsulated crawl space need a dehumidifier?", "Not always. The design should establish how humidity will be controlled and monitored based on the building and climate."],
      ["Should standing water be corrected first?", "Yes. Bulk water and drainage problems should be resolved before a liner conceals the ground."],
      ["Can this site quote encapsulation pricing?", "No. There is no activated operator, and pricing depends on access, size, drainage, repairs, liner details, and equipment."],
    ],
  },
  {
    slug: "hvac-mold-remediation",
    label: "HVAC Mold Remediation",
    keyword: "HVAC mold remediation Houston",
    h1: "HVAC Mold Remediation in Houston, TX",
    group: "HVAC and air",
    priority: true,
    lede: "HVAC mold remediation requires component-specific evaluation. Air handlers, coils, drain pans, insulation, plenums, returns, and duct materials cannot all be approached with the same cleaning method.",
    problemHeading: "Where moisture develops in cooling systems",
    problemText: "Houston's long cooling season produces condensate. Drainage failures, damaged insulation, air leakage, high indoor humidity, and dirty wet components can create persistent moisture near the air system.",
    signals: [
      ["Air handler and drain pan", "Overflow, biofilm, blocked drains, or cabinet leakage can affect nearby insulation and framing."],
      ["Returns and plenums", "Unfiltered air leakage or wet liner can create conditions that differ from a metal supply duct."],
      ["Ducts and boots", "Condensation, damaged insulation, and porous liners require material-specific decisions."],
    ],
    scopeHeading: "Questions an HVAC mold plan should answer",
    scopeText: "The plan should identify the exact component, material, moisture source, system shutdown needs, containment, replace-versus-clean decisions, and which HVAC and remediation professionals are responsible.",
    scopeItems: ["Component and material identification", "Condensate and humidity diagnosis", "System shutdown and isolation", "Cleaning versus replacement criteria", "Post-work operation and monitoring"],
    decisionHeading: "Duct cleaning is not a universal remediation method",
    decisionText: "Routine source removal from suitable ductwork differs from remediation of wet porous liner, contaminated insulation, or growth inside mechanical equipment. The system needs the right scope before cleaning begins.",
    related: ["air-duct-cleaning-mold", "indoor-air-quality-testing", "dehumidification-moisture-control", "attic-mold-remediation", "commercial-mold-remediation", "mold-inspection-testing"],
    faqs: [
      ["Should the HVAC system be run when contamination is suspected?", "Avoid assumptions. If the system is known or strongly suspected to be contaminated, a qualified professional should advise whether operation could spread material."],
      ["Can flexible or internally lined ducts be cleaned?", "Material, condition, contamination, and manufacturer guidance matter. Some porous or damaged components may require replacement."],
      ["Who handles HVAC mold work?", "A project may require both HVAC and mold-remediation expertise. The scope should assign mechanical and remediation responsibilities."],
      ["Does a musty vent odor prove there is mold in the ducts?", "No. Odor can come from several sources. The system and nearby moisture pathways should be evaluated before choosing a service."],
    ],
  },
  {
    slug: "air-duct-cleaning-mold",
    label: "Air Duct Cleaning for Mold Concerns",
    keyword: "air duct cleaning mold Houston",
    h1: "Air Duct Cleaning for Mold Concerns in Houston, TX",
    group: "HVAC and air",
    priority: false,
    lede: "Air duct cleaning can remove accumulated debris from suitable HVAC components, but a mold concern requires diagnosis first. Wet liner, damaged insulation, air-handler contamination, and active condensation can call for more than routine cleaning.",
    problemHeading: "When duct cleaning and mold remediation diverge",
    problemText: "A cleanable metal trunk line is different from flexible duct, internally lined ductboard, a wet plenum, or growth inside an air handler. The material and moisture source determine the defensible approach.",
    signals: [
      ["Visible debris at registers", "Material at a grille does not reveal the condition of the full duct system or mechanical cabinet."],
      ["Musty odor during operation", "An odor tied to system cycles can justify inspection of the air handler, drains, plenums, and duct materials."],
      ["Post-construction dust", "Construction debris may support a source-removal cleaning decision without establishing a mold problem."],
    ],
    scopeHeading: "What a duct-service proposal should specify",
    scopeText: "A credible proposal identifies components included, access methods, agitation and collection equipment, protection of occupied space, material limitations, and any HVAC repairs required before or after cleaning.",
    scopeItems: ["Included supply and return components", "Duct material and condition", "Access opening and closure method", "Negative-air collection and protection", "Mechanical repairs and filter plan"],
    decisionHeading: "Do not use cleaning to bypass a wet-material decision",
    decisionText: "If porous liner or insulation is wet, deteriorated, or contaminated, replacement may be more appropriate than agitation. Assessment should precede a broad cleaning recommendation.",
    related: ["hvac-mold-remediation", "indoor-air-quality-testing", "mold-odor-removal", "dehumidification-moisture-control", "mold-inspection-testing"],
    faqs: [
      ["Does duct cleaning remove all mold from an HVAC system?", "No blanket claim is appropriate. Equipment, liners, insulation, ducts, and moisture sources require separate evaluation."],
      ["How often should ducts be cleaned?", "There is no universal interval. A service decision should be based on confirmed debris, contamination, renovation, pests, or other defined conditions."],
      ["Will cleaning fix duct condensation?", "No. Insulation, air leakage, humidity, airflow, and temperature conditions must be corrected to address condensation."],
      ["Can the ducts be inspected before a quote?", "A provider should confirm the system layout, materials, access, and concern before finalizing a scope."],
    ],
  },
  {
    slug: "water-damage-mold-cleanup",
    label: "Water-Damage Mold Cleanup",
    keyword: "water damage mold cleanup Houston",
    h1: "Water-Damage Mold Cleanup in Houston, TX",
    group: "Core remediation",
    priority: true,
    lede: "Water-damage mold cleanup addresses growth or contaminated materials after leaks, overflows, storms, or delayed drying. The source, water category, elapsed time, and affected assemblies shape the response.",
    problemHeading: "Why the water timeline matters",
    problemText: "Moisture can move under flooring, behind baseboards, into wall cavities, through cabinets, and across insulation. A surface that feels dry may not represent the materials behind it.",
    signals: [
      ["Plumbing leaks and overflows", "Supply lines, drains, appliances, and fixtures can affect hidden cavities and lower floors."],
      ["Roof and storm intrusion", "Wind-driven rain can travel along decking, framing, insulation, and wall assemblies."],
      ["Delayed or incomplete drying", "Wet porous materials can remain a concern after fans are removed or visible water disappears."],
    ],
    scopeHeading: "Separate extraction, drying, and remediation",
    scopeText: "The proposal should clarify emergency water removal, demolition, containment, microbial remediation, drying targets, moisture monitoring, source repair, and reconstruction. These tasks may involve different providers.",
    scopeItems: ["Water source and category", "Elapsed time and prior drying", "Moisture mapping and material condition", "Containment and demolition boundaries", "Drying and reconstruction criteria"],
    decisionHeading: "Active water comes before cosmetic repair",
    decisionText: "Painting, replacing baseboards, or installing new flooring before the assembly is dry and the source is corrected can conceal ongoing damage.",
    related: ["mold-remediation", "residential-mold-remediation", "commercial-mold-remediation", "attic-mold-remediation", "mold-inspection-testing", "dehumidification-moisture-control"],
    faqs: [
      ["How quickly can mold develop after water damage?", "Growth conditions depend on temperature, materials, moisture, and time. Prompt water control and drying reduce risk, but hidden wet materials still need evaluation."],
      ["Is water extraction the same as mold remediation?", "No. Extraction and structural drying address water; remediation addresses contaminated materials and spread control. A project may require both."],
      ["Should wet drywall always be removed?", "The water source, category, duration, material condition, and ability to dry the assembly determine the decision."],
      ["Can storm-related requests be matched immediately?", "Not yet. The site has no live operator or emergency routing, so it must not be used for urgent response until activation is complete."],
    ],
  },
  {
    slug: "mold-inspection-testing",
    label: "Mold Inspection & Testing Coordination",
    keyword: "mold inspection testing Houston",
    h1: "Mold Inspection and Testing in Houston, TX",
    group: "Assessment",
    priority: true,
    lede: "Mold inspection and testing should answer a specific question: what is affected, why it is wet, whether a formal protocol is needed, or how completion will be verified. Sampling without a decision purpose can add cost without clarifying the next step.",
    problemHeading: "When an independent assessment may help",
    problemText: "Large or uncertain scopes, hidden conditions, disputes, real-estate transactions, regulated projects, and post-remediation verification may justify an independent Texas mold assessment consultant.",
    signals: [
      ["Unclear extent", "Inspection and moisture mapping can help define whether the visible area represents a larger concealed condition."],
      ["Formal remediation protocol", "Certain projects may require a licensed assessor to establish the work plan independently of the remediator."],
      ["Clearance or documentation", "Post-remediation review should be performed by the appropriate independent party when required."],
    ],
    scopeHeading: "Testing methods should match the question",
    scopeText: "Air, surface, bulk, and moisture measurements provide different information. A consultant should explain the hypothesis, sampling locations, limitations, comparison basis, and how results will affect recommendations.",
    scopeItems: ["Visual and moisture investigation", "Defined sampling question", "Chain of custody and laboratory method", "Written findings or protocol", "Independent post-work verification"],
    decisionHeading: "Assessment independence matters",
    decisionText: "A service match should distinguish the professional who defines or verifies the work from the company hired to perform remediation when Texas rules or project needs require that separation.",
    related: ["mold-remediation", "indoor-air-quality-testing", "black-mold-remediation", "mold-odor-removal", "commercial-mold-remediation", "post-remediation-verification"],
    faqs: [
      ["Is a home mold test kit enough?", "A kit may produce a result without explaining the source, extent, or appropriate scope. A qualified assessment connects observations and testing to a decision."],
      ["What is a mold remediation protocol?", "It is a written work plan prepared by the appropriate assessor for projects that require one, identifying affected areas, methods, and clearance criteria."],
      ["Can the remediator perform the clearance test?", "Independence requirements can apply. The project should follow Texas rules and the assessment protocol rather than assuming one company fills every role."],
      ["Is testing included in the current matching service?", "No provider is active yet. The form can collect the need, but assessment credentials and coverage must be verified before routing."],
    ],
  },
  {
    slug: "post-remediation-verification",
    label: "Post-Remediation Verification",
    keyword: "post remediation verification Houston",
    h1: "Post-Remediation Verification in Houston, TX",
    group: "Assessment",
    priority: false,
    lede: "Post-remediation verification evaluates whether the completed work meets the protocol or agreed completion criteria. It should be planned before remediation begins so the work area, documentation, and testing conditions are clear.",
    problemHeading: "What verification is intended to confirm",
    problemText: "A verification visit can review cleanliness, remaining affected material, moisture conditions, containment status, project documents, and any sampling required by the protocol.",
    signals: [
      ["Protocol-driven work", "The assessor's written criteria should guide the final review rather than an improvised checklist."],
      ["Third-party requirements", "Owners, buyers, insurers, lenders, or property managers may require independent completion documentation."],
      ["Reconstruction timing", "Clearance should occur before the work area is concealed or rebuilt when the protocol requires access."],
    ],
    scopeHeading: "Prepare the work area for review",
    scopeText: "The remediator should complete cleaning, remove waste, address moisture, and provide requested logs before the assessor arrives. Premature reconstruction can prevent a meaningful visual inspection.",
    scopeItems: ["Protocol and completion criteria", "Visual cleanliness and source correction", "Moisture measurements", "Project logs and disposal records", "Sampling conditions when required"],
    decisionHeading: "A failed verification needs a defined response",
    decisionText: "The assessor should document unmet criteria and identify what must be corrected. Re-cleaning or additional work should be tied to findings rather than vague pass-or-fail language.",
    related: ["mold-inspection-testing", "mold-remediation", "commercial-mold-remediation", "residential-mold-remediation", "indoor-air-quality-testing"],
    faqs: [
      ["When should verification be scheduled?", "Coordinate it before remediation so the assessor, remediator, and owner understand timing, containment, cleaning, and reconstruction constraints."],
      ["Does verification always include air samples?", "No. The protocol and project conditions determine whether sampling is appropriate and which methods are used."],
      ["What happens if the work does not pass?", "The assessor should document the unmet criteria so the remediator can complete targeted corrective work before another review."],
      ["Who should perform verification?", "Use the appropriately licensed and independent professional required by Texas rules and the project protocol."],
    ],
  },
  {
    slug: "black-mold-remediation",
    label: "Black Mold Remediation",
    keyword: "black mold remediation Houston",
    h1: "Black Mold Remediation in Houston, TX",
    group: "Core remediation",
    priority: true,
    lede: "Black mold remediation is a common search phrase, but color is not a species diagnosis or a scope. The defensible response begins with moisture, material, extent, and the need for independent assessment.",
    problemHeading: "What dark growth can and cannot tell you",
    problemText: "Many molds appear dark, and dirt, soot, adhesives, and old water staining can resemble growth. A photograph or color description alone cannot establish identity, exposure, or remediation requirements.",
    signals: [
      ["Dark growth after a leak", "The water history and affected materials provide more useful scope information than color alone."],
      ["Growth inside a cavity", "Hidden extent, insulation, airflow, and access may justify an independent assessment."],
      ["Repeated surface staining", "Recurring marks can point to condensation, humidity, leakage, or incomplete source correction."],
    ],
    scopeHeading: "The remediation plan still follows the material",
    scopeText: "Containment, removal, cleaning, debris control, drying, and verification depend on where the material is and what it is attached to—not whether the growth is described as black.",
    scopeItems: ["Moisture and leak history", "Surface and substrate identification", "Visible and suspected hidden extent", "Independent assessment needs", "Material-specific remediation method"],
    decisionHeading: "Avoid fear-based claims",
    decisionText: "A service provider should not diagnose health effects, identify a species from appearance, or use color alone to justify a larger project. Health questions belong with a qualified medical professional.",
    related: ["mold-remediation", "mold-inspection-testing", "residential-mold-remediation", "water-damage-mold-cleanup", "mold-odor-removal"],
    faqs: [
      ["Can black mold be identified by sight?", "No. Color and appearance are not reliable species identification. A qualified assessor can determine whether sampling would answer a useful question."],
      ["Is dark mold always more dangerous?", "Risk cannot be ranked by color alone. Extent, material, moisture, disturbance, and individual health factors all matter."],
      ["Should dark growth be disturbed for a photo?", "Avoid aggressive scraping or brushing. Document the area without creating unnecessary airborne material."],
      ["Will this site provide health advice?", "No. It provides property-service information only. Discuss symptoms or medical concerns with a qualified healthcare professional."],
    ],
  },
  {
    slug: "indoor-air-quality-testing",
    label: "Indoor Air Quality Testing",
    keyword: "indoor air quality testing Houston",
    h1: "Indoor Air Quality Testing in Houston, TX",
    group: "Assessment",
    priority: false,
    lede: "Indoor air quality testing is broader than mold sampling. A useful investigation starts with symptoms of the building—odors, humidity, ventilation, particles, combustion, or a specific event—and selects measurements that can guide action.",
    problemHeading: "Choose measurements from a defined concern",
    problemText: "A generic panel can produce numbers without explaining the source. Building history, HVAC operation, occupancy, renovations, water events, and outdoor conditions help determine what should be measured.",
    signals: [
      ["Persistent indoor odor", "Odor patterns can point to moisture, drains, materials, smoke, pets, or HVAC pathways."],
      ["Humidity and condensation", "Temperature and relative humidity trends can reveal conditions that support moisture problems."],
      ["Event-based concerns", "Renovation dust, wildfire smoke, a chemical release, or water damage may call for different instruments and specialists."],
    ],
    scopeHeading: "What an IAQ investigation should explain",
    scopeText: "The consultant should identify the question, instruments or samples, locations, timing, outdoor comparison, limitations, and what decisions the findings can support.",
    scopeItems: ["Building and occupant interview", "Temperature, humidity, and ventilation review", "Targeted particles or contaminants", "HVAC and pressure relationships", "Interpretation and action plan"],
    decisionHeading: "IAQ testing does not replace a mold assessment protocol",
    decisionText: "Broader air-quality testing and regulated Texas mold assessment can overlap, but they are not automatically interchangeable. The provider's credentials and deliverable should match the project.",
    related: ["mold-inspection-testing", "hvac-mold-remediation", "air-duct-cleaning-mold", "mold-odor-removal", "dehumidification-moisture-control"],
    faqs: [
      ["What can indoor air quality testing measure?", "Depending on the concern, it may evaluate humidity, particles, carbon dioxide, carbon monoxide, ventilation, volatile compounds, or targeted biological material."],
      ["Does one air sample prove a building is safe?", "No. A limited sample represents specific conditions and timing. Interpretation requires context, limitations, and an investigation plan."],
      ["Is IAQ testing the same as mold testing?", "No. Mold assessment can be one part of an indoor environmental investigation, but licenses, methods, and deliverables may differ."],
      ["Can testing identify an odor source?", "Testing may support the investigation, but source tracing often also requires inspection of moisture, drains, materials, HVAC pathways, and occupancy patterns."],
    ],
  },
  {
    slug: "mold-odor-removal",
    label: "Mold Odor Investigation & Removal",
    keyword: "mold odor removal Houston",
    h1: "Mold Odor Removal in Houston, TX",
    group: "HVAC and air",
    priority: true,
    lede: "Mold odor removal should begin with source investigation. Deodorizers may mask a musty smell temporarily, but persistent odor can indicate damp materials, hidden cavities, drains, contents, or HVAC pathways that need a specific response.",
    problemHeading: "Where a musty odor may originate",
    problemText: "Odor can travel from a crawl space, attic, wall cavity, cabinet, wet carpet pad, HVAC return, or stored belongings. The strongest smelling room is not always the source.",
    signals: [
      ["Odor after rain or cooling cycles", "Timing can connect the smell to roof intrusion, humidity, condensate, pressure, or HVAC operation."],
      ["Odor without visible growth", "Hidden cavities and porous materials may need inspection before any treatment is selected."],
      ["Odor after prior cleanup", "A returning smell can indicate remaining material, incomplete drying, or a source that was never corrected."],
    ],
    scopeHeading: "Separate source removal from odor treatment",
    scopeText: "The plan should identify the suspected source, affected materials, moisture conditions, access needs, cleaning or removal steps, ventilation, and any final odor treatment. Fragrance is not proof of correction.",
    scopeItems: ["Odor pattern and timing", "Moisture and material inspection", "HVAC and pressure pathways", "Source removal or cleaning", "Post-work ventilation and verification"],
    decisionHeading: "Do not promise odor elimination before diagnosis",
    decisionText: "Some odors involve multiple sources or materials. A responsible provider defines the investigation and limitations rather than guaranteeing a result from one treatment.",
    related: ["mold-inspection-testing", "residential-mold-remediation", "hvac-mold-remediation", "air-duct-cleaning-mold", "indoor-air-quality-testing", "water-damage-mold-cleanup"],
    faqs: [
      ["Does a musty smell always mean mold?", "No. Damp materials, drains, soil gases, stored contents, and other sources can smell similar. Inspection should come before a treatment claim."],
      ["Can an ozone machine solve a mold odor?", "A device cannot substitute for locating and correcting contaminated or wet materials. Treatment methods also require safety and material considerations."],
      ["Why does the odor appear only when the HVAC runs?", "System airflow and pressure can move odor from returns, cabinets, cavities, attics, or crawl spaces. The pathway needs investigation."],
      ["Can odor removal be quoted from a photo?", "Usually not. Odor has no visual scale, and the source, materials, extent, and access must be understood first."],
    ],
  },
  {
    slug: "bathroom-mold-remediation",
    label: "Bathroom Mold Remediation",
    keyword: "bathroom mold remediation Houston",
    h1: "Bathroom Mold Remediation in Houston, TX",
    group: "Property-specific",
    priority: false,
    lede: "Bathroom mold remediation depends on whether the issue is routine surface growth, chronic condensation, failed caulk or grout, a plumbing leak, or hidden moisture behind finishes. The visible patch may be only one part of the assembly.",
    problemHeading: "Bathroom moisture has several sources",
    problemText: "Showers, tubs, toilets, supply lines, drains, exterior walls, exhaust fans, and cold surfaces can each create a different moisture pattern and repair responsibility.",
    signals: [
      ["Recurring ceiling growth", "Ventilation, insulation, roof conditions, and condensation may need review before repainting."],
      ["Soft walls or cabinets", "Deterioration near plumbing can suggest long-term leakage behind finishes."],
      ["Growth at caulk and grout", "A small surface issue differs from moisture behind tile backer, flooring, or a shower pan."],
    ],
    scopeHeading: "Match the scope to the assembly",
    scopeText: "The provider should distinguish routine cleaning from demolition, identify leak testing or plumbing needs, protect adjacent rooms, and define how the wall, floor, or shower assembly will be rebuilt.",
    scopeItems: ["Ventilation and condensation", "Supply, drain, and fixture leaks", "Wall and floor material condition", "Containment and access", "Reconstruction and finish responsibilities"],
    decisionHeading: "Cosmetic repair can conceal wet materials",
    decisionText: "New caulk, paint, or grout should not be used to cover an unresolved leak or deteriorated substrate. Moisture correction and material condition come first.",
    related: ["residential-mold-remediation", "water-damage-mold-cleanup", "mold-inspection-testing", "dehumidification-moisture-control", "mold-odor-removal"],
    faqs: [
      ["Can bathroom mold be cleaned without remediation?", "Small routine surface growth may have a different response than damaged drywall, cabinets, subflooring, or a hidden leak. Extent and material matter."],
      ["Does an exhaust fan prevent every bathroom mold issue?", "No. Fan capacity, duct routing, run time, make-up air, insulation, and plumbing conditions all affect moisture."],
      ["Should tile be removed to inspect behind it?", "Only when evidence and assessment support opening the assembly. Unnecessary demolition can increase cost and disturbance."],
      ["Who repairs a shower-pan or plumbing leak?", "A plumber or qualified construction trade may be needed separately from the remediation provider."],
    ],
  },
  {
    slug: "dehumidification-moisture-control",
    label: "Dehumidification & Moisture Control",
    keyword: "dehumidification services Houston",
    h1: "Dehumidification Services in Houston, TX",
    group: "Moisture control",
    priority: true,
    lede: "Dehumidification services manage persistent indoor or enclosed-space humidity after bulk water and active leaks are addressed. Equipment selection should follow diagnosis of ventilation, air leakage, HVAC operation, and the moisture load.",
    problemHeading: "Humidity control starts with the building",
    problemText: "Oversized cooling equipment, negative pressure, outdoor-air leakage, wet crawl spaces, unvented activities, and drainage problems can overwhelm a portable dehumidifier or move moisture elsewhere.",
    signals: [
      ["High relative humidity", "Trend data is more useful than one reading because indoor conditions change with weather and HVAC cycles."],
      ["Condensation on cool surfaces", "Ducts, supply boots, pipes, windows, and walls can reveal temperature and air-leakage issues."],
      ["Persistent damp odor", "Humidity control may be one part of the plan, but wet or contaminated materials still need direct attention."],
    ],
    scopeHeading: "A moisture-control proposal should include targets",
    scopeText: "The plan should state the area served, moisture load assumptions, drainage, power, controls, filtration, maintenance, and target humidity range. Permanent equipment also needs a commissioning and monitoring plan.",
    scopeItems: ["Humidity and temperature trends", "Air leakage and pressure relationships", "HVAC sizing and operation review", "Equipment capacity and drainage", "Controls, maintenance, and monitoring"],
    decisionHeading: "Dehumidification does not remediate contaminated material",
    decisionText: "Lowering humidity can reduce future moisture stress, but it does not remove damaged materials, clean settled contamination, or repair the original water source.",
    related: ["mold-remediation", "crawl-space-encapsulation", "crawl-space-mold-remediation", "hvac-mold-remediation", "indoor-air-quality-testing", "water-damage-mold-cleanup"],
    faqs: [
      ["What indoor humidity level should a home maintain?", "A qualified provider should set a practical range based on the building and season. Avoid relying on a single universal number without context."],
      ["Can a portable dehumidifier solve whole-home humidity?", "It may help a limited area, but capacity, airflow, drainage, air leakage, and HVAC operation determine whether it can control the actual load."],
      ["Will dehumidification kill mold?", "No. Moisture control supports prevention and drying, but affected materials still require an appropriate remediation decision."],
      ["How is equipment capacity selected?", "The provider should consider area volume, temperature, moisture load, infiltration, occupancy, materials, and drainage rather than only square footage."],
    ],
  },
  {
    slug: "specialty-remediation",
    label: "Specialty Mold Remediation",
    keyword: "specialty mold remediation Houston",
    h1: "Specialty Mold Remediation in Houston, TX",
    group: "Property-specific",
    priority: false,
    lede: "Specialty mold remediation covers unusual materials, contents, sensitive collections, vehicles, or spaces that do not fit a standard room-and-drywall scope. The provider must be matched to the material and restoration objective.",
    problemHeading: "Special materials require different decisions",
    problemText: "Documents, artwork, textiles, upholstered contents, wood furniture, instruments, equipment, and historic materials can be damaged by aggressive cleaning or uncontrolled drying.",
    signals: [
      ["Valuable or irreplaceable contents", "Conservation goals and replacement value should be discussed before treatment begins."],
      ["Complex equipment or enclosures", "Mechanical, electrical, and manufacturer requirements can limit cleaning methods."],
      ["Off-site processing needs", "Inventory, packing, transport, controlled cleaning, storage, and return may become part of the project."],
    ],
    scopeHeading: "Build the plan around material compatibility",
    scopeText: "A specialty proposal should describe inventory, condition documentation, testing of cleaning methods, handling, chain of custody, drying, storage, limitations, and criteria for items that cannot be restored.",
    scopeItems: ["Material and value assessment", "Cleaning-method compatibility", "Inventory and chain of custody", "On-site versus off-site processing", "Restoration limitations and disposition"],
    decisionHeading: "Not every item can be restored safely",
    decisionText: "Porosity, deterioration, contamination, finish, value, and intended use affect the decision. A provider should document limitations instead of promising universal recovery.",
    related: ["mold-remediation", "residential-mold-remediation", "commercial-mold-remediation", "water-damage-mold-cleanup", "mold-inspection-testing"],
    faqs: [
      ["Can mold-damaged documents be restored?", "Some documents can be stabilized or treated by specialists, but condition, material, value, and contamination determine what is practical."],
      ["Should contents be moved before containment is built?", "The handling sequence should be planned to avoid spreading material. Inventory and packing may occur under controlled conditions."],
      ["Can upholstered furniture be cleaned?", "Construction, fill material, contamination, condition, and replacement value influence whether cleaning is appropriate."],
      ["How are specialty providers selected?", "Matching should be based on the exact material and service capability, which must be verified after an operator is activated."],
    ],
  },
];

export const areaGroups = [
  {
    slug: "houston-core",
    label: "Houston Core",
    description: "Central and inner-loop properties include older building assemblies, infill construction, flat or low-slope roofs, dense mechanical spaces, and varied drainage histories.",
    areas: [
      ["houston", "Houston"],
      ["downtown-midtown", "Downtown & Midtown"],
      ["the-heights", "The Heights"],
      ["bellaire", "Bellaire"],
      ["west-university-place", "West University Place"],
      ["memorial", "Memorial"],
    ],
  },
  {
    slug: "north-houston",
    label: "North Houston",
    description: "North Houston markets include wooded lots, expanding subdivisions, long rooflines, attic HVAC equipment, and drainage conditions that vary sharply by development.",
    areas: [
      ["the-woodlands", "The Woodlands"],
      ["spring", "Spring"],
      ["tomball", "Tomball"],
      ["conroe", "Conroe"],
    ],
  },
  {
    slug: "northwest-houston",
    label: "Northwest Houston",
    description: "Northwest communities combine master-planned neighborhoods, older subdivisions, storm exposure, slab foundations, and long cooling seasons.",
    areas: [
      ["cypress", "Cypress"],
      ["jersey-village", "Jersey Village"],
      ["copperfield", "Copperfield"],
      ["champions", "Champions"],
    ],
  },
  {
    slug: "west-houston",
    label: "West Houston",
    description: "West Houston coverage candidates include fast-growing communities, mixed building ages, storm-related roof and envelope concerns, and large residential footprints.",
    areas: [
      ["katy", "Katy"],
      ["fulshear", "Fulshear"],
      ["richmond", "Richmond"],
      ["rosenberg", "Rosenberg"],
    ],
  },
  {
    slug: "southwest-houston",
    label: "Southwest Houston",
    description: "Southwest properties range from established neighborhoods to newer development, with plumbing, roof, drainage, and indoor-humidity pathways that require site-specific review.",
    areas: [
      ["sugar-land", "Sugar Land"],
      ["missouri-city", "Missouri City"],
      ["stafford", "Stafford"],
      ["meyerland", "Meyerland"],
    ],
  },
  {
    slug: "southeast-bay-area",
    label: "Southeast & Bay Area",
    description: "Communities closer to the bay face high humidity, wind-driven rain, tropical weather, and building-envelope conditions that can complicate drying and recurrence prevention.",
    areas: [
      ["pearland", "Pearland"],
      ["friendswood", "Friendswood"],
      ["league-city", "League City"],
      ["clear-lake", "Clear Lake"],
      ["pasadena", "Pasadena"],
      ["deer-park", "Deer Park"],
    ],
  },
  {
    slug: "east-northeast-houston",
    label: "East & Northeast Houston",
    description: "East and northeast markets include flood- and storm-exposed corridors, industrial and residential mixes, wooded communities, and varied HVAC and drainage conditions.",
    areas: [
      ["baytown", "Baytown"],
      ["humble", "Humble"],
      ["kingwood", "Kingwood"],
      ["atascocita", "Atascocita"],
      ["channelview", "Channelview"],
    ],
  },
];

export const serviceBySlug = new Map(services.map((service) => [service.slug, service]));
